### PR TITLE
Fixed test coverage on Linux.

### PR DESCRIPTION
**Pull request by felix91gr**
Tests were failing on Linux because... I'm not sure why. I think the way the tests were given to `LinuxMain.swift` wasn't just right.

Anyway, I fixed it. This looks like a cool project! :)

### CODE REVIEW

**Comment by felix91gr** [comment]
Note: I ran the test suite and all tests pass ;)

**Comment by felix91gr** [comment]
I'd need for you to confirm that I didn't mess anything up on the Mac OS side. I think I didn't, but since you don't have CI, and I don't have a Mac, we'd better make sure :)

**Comment by hashemi** [comment]
Thank you @felix91gr

**Comment by felix91gr** [comment]
Np! ;)

**Pull request merged**
